HR/Areas/Payroll/Controllers/PayoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HR.Areas.Payroll.Controllers
{
    public class PayoutController : Controller
    {
        public ActionResult JVQuickBooksOnline()
        {
            return View("JVQuickBooksOnline");
        }
        public ActionResult BankTransfer()
        {
            return View("BankTransfer");
        }
        public ActionResult ChequeCashStatement()
        {
            return View("ChequeCashStatement");
        }
        public ActionResult Payslips()
        {
            return View("Payslips");
        }
        public ActionResult NewBankTransfer()
        {
            return View("NewBankTransfer");
        }
    }
}

HR/Areas/Payroll/Views/Payout/BankTransfer.cshtml
@{
    ViewBag.Title = "BankTransfer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<div class="card-header">
    <h2>
        Bank Transfer
    </h2>

</div>
<div class="card-body card-padding" id="profile-main">
   
    <div class="row m-t-25">
        <div class="col-sm-12 ">
            <div class="" id="profile-main">
                <div class="pm-body clearfix p-0">
                    <div class="form-wizard-basic fw-container">
                        <ul class="tab-nav text-left">
                            <li><a href="#Bank-Transfers" data-toggle="tab">Bank Transfers</a></li>
                            <li><a href="#Void-Transfers" data-toggle="tab"> Void Transfers </a></li>
                            <li><a href="#Pending-Employees" data-toggle="tab">Pending Employees</a></li>
                            
                        </ul>

                        <div class="tab-content">
                            <div class="tab-pane fade" id="Bank-Transfers">

                                <div class="row">
                                    <div class="col-xs-12 col-md-6">
                                        <dl class="dl-horizontal text-left">
                                            <dt style="text-align:left !important;">
                                                Bank transfer pending for 16 employees
                                            </dt>

                                            <dd>




                                            </dd>
                                        </dl>
                                    </div>

                                    <div class="col-xs-12 col-md-6 text-right">
                                        <a href="@Url.Action("NewBankTransfer","Payout",new { area ="Payroll"},null)" class="btn btn-primary waves-effect btn-sm"> Create New Bank Transfer</a>
                                    </div>


                                </div>

                                <div class="table-responsive">
                                    <table class="table table-striped expense-table">
                                        <thead>
                                            <tr>
                                                <th>
                                                    File Name
                                                </th>
                                                <th>Type</th>
                                                <th>Bank</th>
                                                <th>Branch</th>
                                                <th>Employee Count</th>
                                                <th>Total Amount</th>
                                                <th>Date</th>


                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                            </tr>

                                        </tbody>
                                    </table>
                                </div>
                              
                               
                                <div class="row m-t-25">
                                    <div class="col-xs-12 col-md-6">
                                        <dl class="dl-horizontal text-left">
                                            <dt style="text-align:left !important;">
                                                Employee Count : 
                                            </dt>

                                            <dd>
                                                0



                                            </dd>
                                        </dl>
                                    </div>

                                    <div class="col-xs-12 col-md-6 text-right">
                                        <dl class="dl-horizontal text-left">
                                            <dt style="text-align:left !important;">
                                                Total Amount
                                            </dt>

                                            <dd>
                                                Rs 0.00 
                                            </dd>
                                        </dl>  </div>


                                </div>
                            </div>
                            <div class="tab-pane fade" id="Void-Transfers">
                                <div class="table-responsive">
                                    <table class="table table-striped expense-table">
                                        <thead>
                                            <tr>
                                                <th>
                                                    File Name
                                                </th>
                                                <th>Type</th>
                                                <th>Bank</th>
                                                <th>Branch</th>
                                                <th>Employee Count</th>
                                                <th>Total Amount</th>
                                                <th>Date</th>


                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                                <td></td>
                                            </tr>

                                        </tbody>
                                    </table>
                                </div>

                            </div>
                            <div class="tab-pane fade" id="Pending-Employees">
                                <div class="table-responsive">
                                    <table class="table table-striped expense-table">
                                        <thead>
                                            <tr>
                                                <th>
                                                     Name
                                                </th>
                                                <th>Employee No</th>
                                                <th>Bank</th>
                                                <th>Branch</th>
                                                <th>Account No</th>
                                                <th> Amount</th>
                                               


                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>Vinathi</td>
                                                <td>010#</td>
                                                <td>Citi Bank</td>
                                                <td>Hitech</td>
                                                <td>1200012</td>
                                                <td>10,00,000/-</td>
                                              
                                            </tr>

                                        </tbody>
                                    </table>
                                </div>

                            </div>
                           

                            <ul class="fw-footer pagination wizard">
                                @*<li >

                                        <a href="@Url.Action("Salary","PayrollInputs",new { area ="Payroll"},null)" class="btn btn-primary waves-effect btn-sm">

                                            Back To Salary
                                        </a>
                                    </li>*@
                                <li class="previous first">
                                    <a class="a-prevent" href="">
                                        <i class="zmdi zmdi-more-horiz"></i>
                                    </a>
                                </li>
                                <li class="previous">
                                    <a class="a-prevent" href="">
                                        <i class="zmdi zmdi-chevron-left"></i>
                                    </a>
                                </li>
                                <li class="next">
                                    <a class="a-prevent" href="">
                                        <i class="zmdi zmdi-chevron-right"></i>
                                    </a>
                                </li>
                                <li class="next last">
                                    <a class="a-prevent" href="">
                                        <i class="zmdi zmdi-more-horiz"></i>
                                    </a>
                                </li>
                            </ul>

                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

HR/Areas/Payroll/Views/Payout/ChequeCashStatement.cshtml
@{
    ViewBag.Title = "ChequeCashStatement";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="card-header">
    <h2>
        Cash Statement and Tracker
    </h2>

</div>
<div class="card-body card-padding" id="profile-main">
    <div class="card">
        <div class="card-body card-padding">

            <div class="row">
                <div class="col-sm-12 col-md-6">
                    <div class="checkbox m-b-15 ">
                        <label>
                            <input type="checkbox" value="" id="chk1">
                            <i class="input-helper"></i>
                            Select all employees across all pages for the selected filter criteria

                        </label>
                    </div>

                </div>
                <div class="col-sm-12 col-md-2">
                    <div class="form-group fg-line">
                        <label>status</label>
                        <select class="selectpicker" data-live-search="true" title='filter'>
                            <option>All</option>
                            <option>Jan 2017</option>

                        </select>
                    </div>

                </div>
                <div class="col-sm-12 col-md-2">
                    <div class="form-group fg-line">
                        <label>Payment Type</label>
                        <select class="selectpicker" data-live-search="true" title='filter'>
                            <option>cash</option>
                            <option>Jan 2017</option>

                        </select>
                    </div>

                </div>
                <div class="col-sm-12 col-md-2">
                    <div class="form-group fg-line">
                        <label>Employee</label>
                        <select class="selectpicker" data-live-search="true" title='filter'>
                            <option>All</option>
                            <option>Jan 2017</option>

                        </select>
                    </div>

                </div>
            
            </div>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>

                    <th>Employee No</th>
                    <th>Name</th>
                    <th>Net Pay</th>
                    <th>Salary Paid</th>
                    <th>Paid On</th>
                    <th>Remarks</th>
                  
                </tr>
            </thead>
            <tfoot>
                <tr>

                    <th>Component</th>
                    <th>APR</th>
                    <th>MAY</th>
                    <th>JUN</th>
                    <th>JULY</th>
                    <th>AUG</th>
                    <th>SEP</th>
                    <th>OCT</th>
                    <th>NOV</th>
                    <th>DEC</th>
                    <th>JAN</th>
                    <th>FAB</th>
                    <th>MAR</th>
                    <th>TOTAL</th>
                </tr>
            </tfoot>
            <tbody>
                <tr>

                    <td>CONVEYANCE</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>
                    <td>0</td>

                    <td>0</td>
                    <td>0</td>
                    <td>1,548</td>
                    <td>1,600</td>
                    <td>1,600</td>
                    <td>4,748</td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="row m-t-25 text-right">
        <div class="col-xs-12">
            <a href="" class="btn btn-primary waves-effect btn-sm">  Cheque Paid Report</a>

            <a href="" class="btn btn-primary waves-effect btn-sm">  Cheque Unpaid Report</a>

            <a href="" class="btn btn-primary waves-effect btn-sm"> Cheque Paid Voucher</a>

            <a href="" class="btn btn-primary waves-effect btn-sm"> Save</a>
        </div>
    </div>
</div>

HR/Areas/Payroll/Views/Payout/JVQuickBooksOnline.cshtml
@{
    ViewBag.Title = "JVQuickBooksOnline";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>JVQuickBooksOnline</h2>